CREATE TABLE employees
(
 id BIGINT NOT NULL AUTO_INCREMENT,
 name VARCHAR(255),
 age INTEGER,
 gender VARCHAR(255),
 salary FLOAT(53),
 company_id BIGINT,
 PRIMARY KEY (id)
);


CREATE TABLE companies
(
 id BIGINT NOT NULL AUTO_INCREMENT,
 name VARCHAR(255),
 PRIMARY KEY (id)
);


CREATE TABLE todo (
id BIGINT NOT NULL AUTO_INCREMENT,
status VARCHAR(255),
title VARCHAR(255),
PRIMARY KEY (id)
);